### ISSUE TITLE
bigdl-orca, bigdl-chronos Not compatible with pyspark

### ISSUE THREAD

**Issue by bowenzzzzzz** [bowenzzzzzz/BIGDL#1]
Hello, everyone. Anyone could do me a favour? When i import this package some issues appeared. The package i used are as follows:
python 3.8
bigdl-orca: 2.3.0
bigdl-chronos: 2.3.0
pyspark: 2.4.6
The link to the file I refer to is： https://bigdl.readthedocs.io/en/latest/doc/Chronos/Overview/quick-tour.html

The issues are as follws:
>>> from bigdl.orca.automl import hp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/bigdl/orca/__init__.py", line 17, in <module>
    from bigdl.dllib.nncontext import *
  File "/opt/anaconda3/lib/python3.8/site-packages/bigdl/dllib/__init__.py", line 18, in <module>
    prepare_env()
  File "/opt/anaconda3/lib/python3.8/site-packages/bigdl/dllib/utils/engine.py", line 179, in prepare_env
    __prepare_spark_env()
  File "/opt/anaconda3/lib/python3.8/site-packages/bigdl/dllib/utils/engine.py", line 58, in __prepare_spark_env
    if exist_pyspark():
  File "/opt/anaconda3/lib/python3.8/site-packages/bigdl/dllib/utils/engine.py", line 31, in exist_pyspark
    import pyspark
  File "/opt/anaconda3/lib/python3.8/site-packages/pyspark/__init__.py", line 51, in <module>
    from pyspark.context import SparkContext
  File "/opt/anaconda3/lib/python3.8/site-packages/pyspark/context.py", line 31, in <module>
    from pyspark import accumulators
  File "/opt/anaconda3/lib/python3.8/site-packages/pyspark/accumulators.py", line 97, in <module>
    from pyspark.serializers import read_int, PickleSerializer
  File "/opt/anaconda3/lib/python3.8/site-packages/pyspark/serializers.py", line 72, in <module>
    from pyspark import cloudpickle
  File "/opt/anaconda3/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 145, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/opt/anaconda3/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 126, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

**Comment by hkvision** [comment]
Hi @bowenzzzzzz 

Pyspark 2.4.6 itself is not compatible with Python 3.8.
You can use Python 3.7 instead. Or if you really want to use Python 3.8, you can install bigdl-orca-spark3&bigdl-chronos-spark3, which are built on top of Pyspark3, should work with Python 3.8.

Feel free to tell us if you have further questions :)

**Comment by bowenzzzzzz** [comment]
Hi, hkvision, Thanks for your support. I tried the two methods you suggested. Everything goes well.Thanks you so much.

**Comment by hkvision** [comment]
Great! Tell us if you have issues in the future!
